### ISSUE TITLE
Crash when using MediaPortal screen blanking

### ISSUE THREAD

**Issue by Shukuyen** [MPExtended/WifiRemote#13]
Bug report by johan in this pull request: https://github.com/MPExtended/WifiRemote/pull/11#issuecomment-31485597

> I noticed an issue with WifiRemote/MediaPortal when using screen
> blanking in MP. Starting media using WifiRemote when the screen is blank
> trigger strange things. E.g. I got a crash when starting a tv serie when
> the refresh changes kicked in. Starting playlist track throw a Last.fm
> error and so on. A workaround that works for me is to send a keystroke
> before the play command. But it should preferably be handled in
> WifiRemote.

With my follow-up questions:

> Not sure I can follow what exactly the problem is (my MediaPortal setup is pretty basic, no fancy refresh rate changer stuff and the like ;)). We have something in WifiRemote to cancel the screensaver on incoming commands:
> https://github.com/MPExtended/WifiRemote/blob/develop/Sources/WifiRemote/Core/SocketServer.cs#L575
> 
> For this we simulate a left-control-key press. But this isn't what you are after, right?

And his answer to that:

> I can check the exact settings in mediaportal config this evening, but I
> think it's with gui settings. One can reduce framrate or blank screen.
> Use the blank screen setting and set the timeout to e.g. 5-10 seconds.
> Then start media through WifiRemote.
> 
> The left-control-key press should do the same as I did as workaround
> with only difference of timing of the commands and a different key.
> Maybe there need to be a longer delay between the key command and the
> play command? The workaround worked for me but not for Joost for music
> playlists, it was he that experienced the problem and I could reproduce it.
> 
> I can take a look later to see if one can turn off the screen saver in a
> better way.

**Comment by johanj** [comment]
I just made a pull request for the screen blanking issue.
