### ISSUE TITLE
TV Now playing message brake zero button for switching to previous channel

### ISSUE THREAD

**Issue by johanj** [MPExtended/WifiRemote#15]
For updating the channel we use:  TvPlugin.TVHome.Navigator.UpdateCurrentChannel()
This seems to update previous channel to the current one so the feature with zero button on keyboard no longer work. 

I have tried to retrieve the active channel in another way but I haven't succeded yet.

**Comment by Shukuyen** [comment]
Fixed with https://github.com/MPExtended/WifiRemote/pull/16
