### ISSUE TITLE
#selecteditem displayed as SelectedItem in Titan skin basichome

### ISSUE THREAD

**Issue by Shukuyen** [MPExtended/WifiRemote#23]
Basichome menu items in Titan skin are displayed as #selecteditem in WifiRemote, instead of "Music" or something like that. Works in other skins, so not sure that is something we can fix. But maybe we can find the cause and file a bug for the skin.

@DieBagger and @johanj any ideas?

**Comment by johanj** [comment]
I can ask Nico.

**Comment by Shukuyen** [comment]
I don't know who that is but any help would be appreciated :)

**Comment by johanj** [comment]
Nico is the guy that implemented the Titan and Maya skins:)

**Comment by johanj** [comment]
I have emailed him.

**Comment by Shukuyen** [comment]
Great, thanks!

**Comment by johanj** [comment]
Message from Nico: Yes, that`s because we use a process plugin to render the BasicHome. That will be fixed in Titan TNC.

Nico

**Comment by Shukuyen** [comment]
Ok thanks, so all we can do about that right now is wait :)
