### ISSUE TITLE
"playmovie" or "playepisode"

### ISSUE THREAD

**Issue by maikkley** [MPExtended/WifiRemote#25]
When i send a command like:

```
{ 
    "Type":"movingpictures", 
    "Action":"playmovie", 
    "MovieId":4 
} 
```

The movie doenst play! API-Version 12.
Is there a known issue?

**Comment by Shukuyen** [comment]
Nothing I know of yet, no. @DieBagger or @johanj do you know of any issue here?

**Comment by johanj** [comment]
The command above looks right and we use it in MPiV without issues. 

One alternative is to use a playlist.  
-playlist clear
-mpext enque id mediatype provider etc.
-playlist play 

I have however had issues with the playfile command where the file started to play in MP. But, Mp crached when stopping media.

**Comment by maikkley** [comment]
Mhhh, i tested it with MP 1.8.0 and WifiRemote API 12... maybe its an issue of the constellation.
I will test this again...

_Edit_
Is there a logfile for WifiRemote? Where i can find it?

**Comment by maikkley** [comment]
As "MovieId" i passed the MpExtended MovieId,is it right?

**Comment by maikkley** [comment]
Found it!
In my code i make "JSON.stringify" of the command, this converts the MovieId 4 to a string "4".
This is not accepted in WifiRemote. There is no casting vom string to int32.

**Comment by johanj** [comment]
I checked that in your example and there you have an int and no string;) Good that it works now.

Logging is made in the standard MediaPortal log.

**Comment by maikkley** [comment]
Yes i my example it was right, but before i send the Command i make a JSON.stringify. That makes the int32 to a String :-/
